"""Add summary to film

Revision ID: 21597e1065c8
Revises: 913dfc337800
Create Date: 2024-03-10 14:42:39.885422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21597e1065c8'
down_revision: Union[str, None] = '913dfc337800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'summary')
    # ### end Alembic commands ###
